/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "platform.h"

#define APB2ENR_BASE 0X40021000
#define GPIO_PA_BASE 0X40010800

#define IOPAEN (1<<2)
#define PA_PIN13  (1UL<<13)


/* method_1
vusint32 *APBptr= NULL;
vusint32 *CRHptr= NULL;
vusint32 *ODRptr= NULL;*/

#define APBptr *((vusint32*)(APB2ENR_BASE + 0X18))
#define CRHptr *((vusint32*)(GPIO_PA_BASE + 0X04))
#define ODRptr *((vusint32*)(GPIO_PA_BASE + 0X0C))





int main(void)
{
/*	method_1
    APBptr = (vusint32*)(APB2ENR_BASE + 0X18);
	CRHptr = (vusint32*)(GPIO_PA_BASE + 0X04);
	ODRptr = (vusint32*)(GPIO_PA_BASE + 0X0C);*/

/*	method_1
    *APBptr |= IOPAEN;
	*CRHptr &= 0XFF0FFFFF;
	*CRHptr |= 0X00200000;*/
APBptr |= IOPAEN;
CRHptr &= 0XFF0FFFFF;
CRHptr |= 0X00200000;


	while(1)
	{
		int i ;
		/*
		 * *ODRptr |=  PA_PIN13;*/
		ODRptr |=  PA_PIN13;
		for (i=0 ; i<5000 ; i++);
		/*
		 * *ODRptr &= ~(PA_PIN13);*/
		ODRptr &= ~(PA_PIN13);
		for (i=0 ; i<5000 ; i++);
	}

}


